server:
  port: 8081

spring:
  ai:
    mcp:
      server:
        enabled: true
        name: chess-mcp
        version: 1.0.0
        type: SYNC

chess:
  coreBaseUrl: http://localhost:8080
  activeUserPath: /chessjourney/activeUser
  quotePath: /chessjourney/quote
